### ISSUE TITLE
ECI to ECEF

### ISSUE THREAD

**Issue by stephenHartzell** [brandon-rhodes/python-novas#10]
Is there a way to do ECI to ECEF conversions with this software that includes the nutation, polar, precession, and sideral rotations?

**Comment by brandon-rhodes** [comment]
I am not sure — though I put NOVAS up here on GitHub, I am far from an expert on everything it can do. Try looking through the official documentation, it might be able to clarify what it does and does not do:

http://aa.usno.navy.mil/software/novas/novas_py/novaspy_intro.php

Good luck with your calculations!
