### ISSUE TITLE
cel_pole type is {1, 2} not {0, 1}

### ISSUE THREAD

**Issue by mslonina** [brandon-rhodes/python-novas#11]
Hi,

the cel_pole wrapper throws error when specifying cel_pole offset options - the Novas implementation requires options to be either 1 or 2, properly noted in compat.py, but the option checker requires 0 or 1.

https://github.com/brandon-rhodes/python-novas/blob/6a93953c92bb43dd28a488d2a8baa86eee386eab/compat/compat.py#L2019

**Comment by brandon-rhodes** [comment]
Thanks, I've merged your pull request! :)
