### ISSUE TITLE
python-novas DE405 seems to differ from JPL DE405

### ISSUE THREAD

**Issue by tomdean1** [brandon-rhodes/python-novas#14]
The constant names in python-novas DE405 are different from 
ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de405/header.405

It appears that denum is in a different location, or missing.
A de405 generated with jplbin.h and the associated c files is the same size as python3.5/dist-packages/novas_de405/DE405.bin
But, /usr/bin/hd shows the contents of the two files to differ.
Was this change made for some reason?

**Comment by brandon-rhodes** [comment]
How are you printing the constant names? I just glanced back over the NOVAS Guide PDF and searched for each occurrence of the word "constant" but didn't find any facility that the Naval Observatory provided for listing the constants in an ephemeris.

I don't know what decisions were made when they generated any particular version of DE405 but I have indeed noticed differences between different versions of a single ephemeris before — for example, between the binary distributed from the JPL and the one that can be downloaded from a list of SPICE ephemerides.

**Comment by brandon-rhodes** [comment]
I'm still interested in learning how to print the constants so that I can compare them! In the meantime I'm going to temporarily close this issue to keep my dashboard clear. Simply re-open it once you have more information for me. Thanks!
