### ISSUE TITLE
Getting this error while installing it on windows using pip

### ISSUE THREAD

**Issue by six-eyes-dev** [brandon-rhodes/python-novas#19]
E:\General_Computer_Science>myenv\Scripts\activate

(myenv) E:\General_Computer_Science>pip install novas
Collecting novas
  Using cached novas-3.1.1.6.tar.gz (141 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\stude\AppData\Local\Temp\pip-install-ikub5lhj\novas_cfc39934b35f499a8a80c111090baac8\setup.py", line 220, in <module>        
          main()
        File "C:\Users\stude\AppData\Local\Temp\pip-install-ikub5lhj\novas_cfc39934b35f499a8a80c111090baac8\setup.py", line 144, in main
          raise OSError("Operating system not supported at this time")
      OSError: Operating system not supported at this time
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by brandon-rhodes** [comment]
The error message is, alas, accurate:

```
OSError: Operating system not supported at this time
```

The Naval Observatory lists the compatible operating systems on its website:

https://aa.usno.navy.mil/software/novaspy_intro

"NOVAS Python is currently available for Mac OSX, Linux, and Unix at the Astrophysics Source Code Library."

As this is the installer's expected behavior, I'll go ahead and close this issue for you.
