### ISSUE TITLE
cio_location crashes it NameError

### ISSUE THREAD

**Issue by alexamici** [brandon-rhodes/python-novas#8]
I think this is not the upstream repository so this bug may not belong here, but I didn't find any bug reporting option here: http://aa.usno.navy.mil/software/novas/novas_py/novaspy_intro.php

A simple attempt to call novas.compat.cio_location crashes with a strange NameError:

```
>>> novas.compat.cio_location(novas.constants.T0)
NameError                                 Traceback (most recent call last)
<ipython-input-45-424d4effe030> in <module>()
----> 1 novas.compat.cio_location(novas.constants.T0)

[...]/novas/compat/compat.py in cio_location(jd_tdb, accuracy)
   2716 
   2717     ra_cio = c_double()
-> 2718     ref_sys - c_short()
   2719 
   2720     return_value = _cio_location(jd_tdb, accuracy, byref(ra_cio),

NameError: name 'ref_sys' is not defined
```

FYI I fresh installed novas and successfully run the self test with:

```
python -m unittest discover novas
................................................................................................................................................................................................
----------------------------------------------------------------------
Ran 193 tests in 0.024s

OK
```

I'll report the bug upstream myself if you point me to the proper way to do it. Thanks.

**Comment by alexamici** [comment]
Looks line https://github.com/brandon-rhodes/python-novas/blob/master/compat/compat.py#L2718 should read:

    ref_sys = c_short()

**Comment by brandon-rhodes** [comment]
Happily, this has now been fixed upstream, and I am about to release a new version of this NOVAS package to PyPI with the fix included. Thanks so much for pointing it out and tracking down the correct fix!
